---
- hosts: blog
  vars:
    letsencrypt_email: outsideris@gmail.com
    domain_name: blog.outsider.ne.kr
    root_domain_name: outsider.ne.kr

  tasks:
  - name: install letsencrypt
    apt: name=letsencrypt state=latest
    become: true

  - name: create letsencrypt directory
    file: name=/var/www/letsencrypt state=directory
    become: true

  - name: reload nginx
    service: name=nginx state=restarted
    become: true

  - name: install snapd
    shell: snap install core
    become: true

  - name: refresh snapd
    shell: snap refresh core
    become: true

  - name: install certbot
    shell: snap install --classic certbot
    become: true

  - name: install packages
    apt:
      pkg:
        - python3-certbot-nginx
      update_cache: yes
    become: true

  - name: create letsencrypt certificate
    shell: certbot --nginx -n -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}
    become: true

  - name: create letsencrypt certificate for root
    shell: certbot --nginx -n -m {{ letsencrypt_email }} --agree-tos -d {{ root_domain_name }}
    become: true

  - name: Generate dhparams
    shell: openssl dhparam -out /etc/nginx/dhparams.pem 2048
    args:
      creates: /etc/nginx/dhparams.pem
    become: true

  - name: add nginx blog SSL configurations
    template:
      src: ./templates/blog-https.conf.j2
      dest: /etc/nginx/sites-enabled/blog-https.conf
      owner: root
      group: root
      mode: 0644
    become: true

  - name: add nginx root SSL configurations
    template:
      src: ./templates/root-https.conf.j2
      dest: /etc/nginx/sites-enabled/root-https.conf
      owner: root
      group: root
      mode: 0644
    become: true

  - name: reload nginx
    service: name=nginx state=restarted
    become: true

  - name: add letsencrypt cronjob for cert renewal
    cron:
      name: letsencrypt_renewal
      special_time: weekly
      job: certbot certonly --nginx && service nginx reload
    become: true

  - name: overwrite to redirect http to https
    template:
      src: ./templates/blog-301.conf.j2
      dest: /etc/nginx/sites-enabled/blog.conf
      owner: root
      group: root
      mode: 0644
    become: true
